# -*- coding: utf-8 -*-
"""A090D105_1003 .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FCQBvAzkqmc8R8jg4aq3IM3B5sq6qq35

# HASH 雜湊函數
陳嘉翔 

1005
- md5
- sha1



- linux指令
- md5sum
- Colab使用方式 : !md5sum 檔案名稱
"""

!md5sum --help

!echo  Tainan人 > 1005.txt

!cat 1005.txt

!md5sum 1005.txt

!echo tainan人 > 1005a.txt

!cat 1005a.txt

!md5sum 1005a.txt